import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BottomNav from '@/components/BottomNav/BottomNav';
import HeaderNav from '@/components/HeaderNav/HeaderNav';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Vital Fit",
  description: "Generated by Vital Fit",
  generator: "Next.Js",
  manifest: "/manifest.json",
  keywords: ["nextjs", "next15", "pwa", "next-pwa"],
  icons: [
    { rel: "apple-touch-icon", url: "icons/vitalfit-512.png" },
    { rel: "icon", url: "icons/vitalfit-512.png" },
  ]
}

export const generateViewport = (): Viewport => ({
  themeColor: "#2ECC71",
  width: "device-width",
  initialScale: 1,
  minimumScale: 1,
  viewportFit: "cover",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
        <link rel="icon" href="icons/vitalfit-512.png" />
        <link rel="apple-touch-icon" href="icons/vitalfit-512.png" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav style={{
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'space-between',
          height: '100vh'
        }}>
          <div style={{
            width: '100%'
          }}>
            <HeaderNav />
            {children}
          </div>

          <BottomNav />
        </nav>
      </body>
    </html>
  )
}
